"""The vendored JLPT kanji list.

Not testing the upstream dataset — that is someone else's repository and it is
right often enough. What is worth guarding is the *derivation*: the file in
`app/data/` is generated by hand from a 5MB source, and a re-derivation that
silently drops a tier or mangles an encoding would show up as a coverage bar
quietly reading wrong rather than as anything failing.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

DATA = Path(__file__).resolve().parent.parent / "app" / "data" / "jlpt_kanji.json"


@pytest.fixture(scope="module")
def payload() -> dict:
    return json.loads(DATA.read_text(encoding="utf-8"))


def test_attribution_survives_a_re_derivation(payload):
    """MIT obliges us to keep the notice with the data, so it is part of the file."""
    source = payload["_source"]
    assert source["license"] == "MIT"
    assert "David Gouveia" in source["copyright"]
    assert source["repository"].startswith("https://github.com/")


def test_every_tier_is_a_real_jlpt_level(payload):
    tiers = set(payload["levels"].values())
    assert tiers == {1, 2, 3, 4, 5}


def test_the_counts_match_the_published_lists(payload):
    """The post-2010 five-tier lists, which have been stable since the reform.

    Hard-coded rather than derived: the point is to notice if a re-derivation
    changes them, and a test that recomputes the number it checks notices
    nothing.
    """
    counts = {tier: 0 for tier in range(1, 6)}
    for tier in payload["levels"].values():
        counts[tier] += 1

    assert counts == {5: 79, 4: 166, 3: 367, 2: 367, 1: 1232}
    assert sum(counts.values()) == 2211


def test_anchors_are_where_they_should_be(payload):
    """A handful of kanji whose tier is not in doubt.

    Catches the encoding failure this file is most exposed to: if the keys were
    ever written through a non-UTF-8 codec, every lookup would miss and the
    backfill would report zero matches rather than an error.
    """
    levels = payload["levels"]
    assert levels["一"] == 5
    assert levels["日"] == 5
    assert levels["愛"] == 3
    # Outside every list, and so absent rather than present-and-null.
    assert "鬱" not in levels


def test_wanikani_levels_are_a_subset_with_plausible_values(payload):
    """`wanikaniLevels` is the drift check the backfill runs; it has to line up."""
    levels, wk = payload["levels"], payload["wanikaniLevels"]

    assert set(wk).issubset(set(levels))
    # WaniKani has 60 levels and has had for years.
    assert all(1 <= level <= 60 for level in wk.values())
    # WaniKani teaches most but not all JLPT kanji — the gap is the N1 tail, and
    # it is the whole reason the full list is vendored rather than the subset.
    assert len(wk) == 1950
