"""initial schema

Revision ID: 2da9b14da58f
Revises: 
Create Date: 2026-08-30 08:13:13.191688

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2da9b14da58f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('characters', sa.String(length=32), nullable=True),
    sa.Column('character_image_url', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), server_default='', nullable=False),
    sa.Column('meanings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('readings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('meaning_mnemonic', sa.Text(), nullable=True),
    sa.Column('reading_mnemonic', sa.Text(), nullable=True),
    sa.Column('meaning_hint', sa.Text(), nullable=True),
    sa.Column('reading_hint', sa.Text(), nullable=True),
    sa.Column('component_subject_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('amalgamation_subject_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('jlpt_level', sa.Integer(), nullable=True),
    sa.Column('data_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index('ix_subjects_jlpt_level', 'subjects', ['jlpt_level'], unique=False)
    op.create_index('ix_subjects_level', 'subjects', ['level'], unique=False)
    op.create_index('ix_subjects_type', 'subjects', ['type'], unique=False)
    op.create_table('sync_meta',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wanikani_user_id', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('max_level_granted', sa.Integer(), nullable=False),
    sa.Column('subscription_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wanikani_user_id')
    )
    op.create_table('study_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('srs_stage', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('burned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'assignment_id', name='uq_progress_user_assignment')
    )
    op.create_index('ix_progress_available_at', 'study_progress', ['user_id', 'available_at'], unique=False)
    op.create_index('ix_progress_started_at', 'study_progress', ['user_id', 'started_at'], unique=False)
    op.create_table('vocab_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_uri', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('jlpt_level', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocab_sources_user_status', 'vocab_sources', ['user_id', 'status'], unique=False)
    op.create_table('reviews_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('study_progress_id', sa.Integer(), nullable=False),
    sa.Column('incorrect_meaning', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('incorrect_reading', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('starting_srs_stage', sa.Integer(), nullable=True),
    sa.Column('ending_srs_stage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_progress_id'], ['study_progress.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_log_created_at', 'reviews_log', ['created_at'], unique=False)
    op.create_table('vocab_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('wanikani_subject_id', sa.Integer(), nullable=True),
    sa.Column('kanji_furigana', sa.String(length=64), nullable=False),
    sa.Column('furigana_only', sa.String(length=64), server_default='', nullable=False),
    sa.Column('english', sa.Text(), server_default='', nullable=False),
    sa.Column('source_image_id', sa.Integer(), nullable=True),
    sa.Column('is_user_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('jlpt_level', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_image_id'], ['vocab_sources.id'], ),
    sa.ForeignKeyConstraint(['wanikani_subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wanikani_subject_id')
    )
    op.create_index('ix_vocab_items_jlpt_level', 'vocab_items', ['jlpt_level'], unique=False)
    op.create_index('ix_vocab_items_source', 'vocab_items', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vocab_items_source', table_name='vocab_items')
    op.drop_index('ix_vocab_items_jlpt_level', table_name='vocab_items')
    op.drop_table('vocab_items')
    op.drop_index('ix_reviews_log_created_at', table_name='reviews_log')
    op.drop_table('reviews_log')
    op.drop_index('ix_vocab_sources_user_status', table_name='vocab_sources')
    op.drop_table('vocab_sources')
    op.drop_index('ix_progress_started_at', table_name='study_progress')
    op.drop_index('ix_progress_available_at', table_name='study_progress')
    op.drop_table('study_progress')
    op.drop_table('users')
    op.drop_table('sync_meta')
    op.drop_index('ix_subjects_type', table_name='subjects')
    op.drop_index('ix_subjects_level', table_name='subjects')
    op.drop_index('ix_subjects_jlpt_level', table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
