"""questions and lesson bundles

Revision ID: 3413a054bc88
Revises: a1c7e33b90f4
Create Date: 2026-09-10 00:08:07.163298

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3413a054bc88'
down_revision: str | Sequence[str] | None = 'a1c7e33b90f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('consumed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_lesson_bundles_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lesson_bundles_user_consumed', 'lesson_bundles', ['user_id', 'consumed'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grammar_entry_id', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verifier_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grammar_entry_id'], ['grammar_entries.id'], name='fk_questions_grammar_entry_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_questions_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_user_verified', 'questions', ['user_id', 'verified'], unique=False)
    op.create_table('lesson_bundle_questions',
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['lesson_bundles.id'], name='fk_lesson_bundle_questions_bundle_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='fk_lesson_bundle_questions_question_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bundle_id', 'question_id')
    )
    op.create_table('question_vocab_items',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('vocab_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='fk_question_vocab_items_question_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocab_item_id'], ['vocab_items.id'], name='fk_question_vocab_items_vocab_item_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'vocab_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_vocab_items')
    op.drop_table('lesson_bundle_questions')
    op.drop_index('ix_questions_user_verified', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_lesson_bundles_user_consumed', table_name='lesson_bundles')
    op.drop_table('lesson_bundles')
    # ### end Alembic commands ###
