"""vocab_sources.image_uri is nullable

Revision ID: 3ff132e7ce86
Revises: 2da9b14da58f
Create Date: 2026-08-30 21:21:18.526984

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3ff132e7ce86'
down_revision: str | Sequence[str] | None = '2da9b14da58f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vocab_sources', 'image_uri',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Reinstating NOT NULL fails if any row has a null `image_uri` — which every
    row written while the photo was buffered in memory does. Clear them first,
    or accept that this direction is only available on a fresh database.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vocab_sources', 'image_uri',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
