"""vocab sets, answers and SRS state

Revision ID: 94753d45601c
Revises: dff614418157
Create Date: 2026-08-30 22:57:52.226438

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '94753d45601c'
down_revision: str | Sequence[str] | None = 'dff614418157'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_vocab_sets_user_name')
    )
    op.create_table('srs_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocab_item_id', sa.Integer(), nullable=False),
    sa.Column('skill_type', sa.String(length=16), nullable=False),
    sa.Column('ease_factor', sa.Float(), server_default=sa.text('2.5'), nullable=False),
    sa.Column('interval_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('repetitions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lapses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reviews_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reviews_correct', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocab_item_id'], ['vocab_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vocab_item_id', 'skill_type', name='uq_srs_state_user_item_skill')
    )
    op.create_index('ix_srs_state_due', 'srs_state', ['user_id', 'due_at'], unique=False)
    op.create_table('vocab_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocab_item_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('accepted', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['vocab_item_id'], ['vocab_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vocab_item_id', 'kind', 'value', name='uq_vocab_answer')
    )
    op.create_index('ix_vocab_answers_item', 'vocab_answers', ['vocab_item_id'], unique=False)
    op.create_table('vocab_set_items',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('vocab_item_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['vocab_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocab_item_id'], ['vocab_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_id', 'vocab_item_id')
    )
    op.create_table('vocab_review_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('srs_state_id', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('answer_given', sa.String(length=256), nullable=True),
    sa.Column('interval_before_days', sa.Integer(), nullable=False),
    sa.Column('interval_after_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['srs_state_id'], ['srs_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocab_review_log_created_at', 'vocab_review_log', ['created_at'], unique=False)
    op.add_column('vocab_sources', sa.Column('set_id', sa.Integer(), nullable=True))
    op.add_column('vocab_sources', sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_foreign_key('fk_vocab_sources_set_id', 'vocab_sources', 'vocab_sets', ['set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_vocab_sources_set_id', 'vocab_sources', type_='foreignkey')
    op.drop_column('vocab_sources', 'position')
    op.drop_column('vocab_sources', 'set_id')
    op.drop_index('ix_vocab_review_log_created_at', table_name='vocab_review_log')
    op.drop_table('vocab_review_log')
    op.drop_table('vocab_set_items')
    op.drop_index('ix_vocab_answers_item', table_name='vocab_answers')
    op.drop_table('vocab_answers')
    op.drop_index('ix_srs_state_due', table_name='srs_state')
    op.drop_table('srs_state')
    op.drop_table('vocab_sets')
    # ### end Alembic commands ###
