"""vocab_items.usage_context

Revision ID: dff614418157
Revises: 3ff132e7ce86
Create Date: 2026-08-30 21:47:00.100261

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'dff614418157'
down_revision: str | Sequence[str] | None = '3ff132e7ce86'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocab_items', sa.Column('usage_context', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocab_items', 'usage_context')
    # ### end Alembic commands ###
